### ISSUE TITLE
Crazy_river

### ISSUE THREAD

**Issue by darioemb** [NicolaDes/ariadneExample#2]
The system works has expected nevertheless when reach  an overflow state it blocks the system.
![crazy](https://user-images.githubusercontent.com/30407873/39811714-12cdd442-538a-11e8-8f4b-c496e6e0f005.jpg)

Above we show the third tank time execution that underling the fact that the overflows of first and second tanks make the reachable set growing, as we not expected.

**Comment by lgeretti** [comment]
Using a step size of 0.1 instead of 0.5 solves the explosion in the number of trajectories, giving the following figure (variables 0 and 3):

![upper_reach 0 3](https://user-images.githubusercontent.com/1506092/40234930-d7b9327c-5aa8-11e8-9d7a-232fec24c195.png)

**Comment by darioemb** [comment]
Again Thank you.
Similarly to the lock_system everything works well and fine.
